name = "datadog-config-api"
main = "datadog-config.js"
compatibility_date = "2024-01-01"

[env.production]
route = "api.ramseymcgrath.com/datadog-config"

[env.development]
route = "dev-api.ramseymcgrath.com/datadog-config"

[[env.production.vars]]
APP_VERSION = "1.0.0"

[[env.development.vars]]
APP_VERSION = "1.0.0-dev"
