name: Pre-commit

on:
  push:
    branches: [ main, advanced-behavior-handling ]
  pull_request:
    branches: [ main ]

jobs:
  pre-commit:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    
    - name: Install pre-commit
      run: |
        python -m pip install --upgrade pip
        pip install pre-commit
    
    - name: Cache pre-commit hooks
      uses: actions/cache@v4
      with:
        path: ~/.cache/pre-commit
        key: pre-commit-${{ runner.os }}-${{ hashFiles('.pre-commit-config.yaml') }}
        restore-keys: |
          pre-commit-${{ runner.os }}-
    
    - name: Run pre-commit on all files
      run: |
        pre-commit run --all-files --show-diff-on-failure
    
    - name: Run pre-commit autoupdate (on schedule)
      if: github.event_name == 'schedule'
      run: |
        pre-commit autoupdate
        
        # Check if there are changes
        if ! git diff --quiet .pre-commit-config.yaml; then
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .pre-commit-config.yaml
          git commit -m "🤖 Update pre-commit hooks"
          git push
        fi