name: Security

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    # Run weekly security scans on Mondays at 00:00 UTC
    - cron: '0 0 * * 1'

permissions:
  actions: read
  contents: read
  security-events: write

jobs:
  # NOTE: CodeQL analysis is now handled in consolidated-ci.yml
  # This workflow focuses on dependency security and SAST
  
  dependency-review:
    name: Dependency Review
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v5
      with:
        submodules: recursive
    
    - name: Dependency Review
      uses: actions/dependency-review-action@v4
      with:
        fail-on-severity: moderate
        allow-licenses: MIT, BSD-2-Clause, BSD-3-Clause, Apache-2.0, ISC, GPL-3.0

  security-audit:
    name: Security Audit
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v5
      with:
        submodules: recursive
    
    - name: Set up Python
      uses: actions/setup-python@v6
      with:
        python-version: '3.11'
        cache: 'pip'
    
    - name: Install security tools
      run: |
        python -m pip install --upgrade pip
        pip install safety bandit semgrep
    
    - name: Run Safety (dependency vulnerabilities)
      run: |
        safety check --json --output safety-report.json || true
        safety check || echo "Safety found vulnerabilities - check report"
      continue-on-error: true
    
    - name: Run Bandit (code security issues)
      run: |
        bandit -r src/ -f json -o bandit-report.json || true
        bandit -r src/ -f sarif -o bandit-report.sarif || true
        bandit -r src/ || echo "Bandit found security issues - check report"
      continue-on-error: true
    
    - name: Upload Bandit SARIF
      uses: github/codeql-action/upload-sarif@v3
      if: always()
      with:
        sarif_file: bandit-report.sarif
        category: bandit
      continue-on-error: true
    
    - name: Run Semgrep (SAST)
      run: |
        semgrep --config=auto src/ --json --output=semgrep-report.json || true
        semgrep --config=auto src/ --sarif --output=semgrep-report.sarif || true
        semgrep --config=auto src/ || echo "Semgrep found issues - check report"
      continue-on-error: true
    
    - name: Upload Semgrep SARIF
      uses: github/codeql-action/upload-sarif@v3
      if: always()
      with:
        sarif_file: semgrep-report.sarif
        category: semgrep
      continue-on-error: true
    
    - name: Upload security reports
      uses: actions/upload-artifact@v5
      if: always()
      with:
        name: security-reports
        path: |
          safety-report.json
          bandit-report.json
          bandit-report.sarif
          semgrep-report.json
          semgrep-report.sarif
        retention-days: 30